baseURL: "https://axthauvin.onrender.com/"
languageCode: fr
title: Axel Thauvin
paginate: 4
theme: "hugo-PaperMod"

defaultContentLanguage: fr

languages:
  fr:
      languageName : Français
      weight: 1
      params:
        languageAltTitle : Français
  en:
      languageName : en
      weight: 2
      
      params :
          dateFormat : January 2, 2006
          languageAltTitle : English
          homeInfoParams :
              Title : Axel Thauvin
              ImageCover : "../ID_axel_carre.png"
              Subtitle : Student in 3rd year at EPITA
              LastNews : Latest projects 📰
              Contents :
                  - text: Here I will post [***my projects***](../projects), as well as my various offers of [***online courses***](/cours).
                  - text: You can find my *resume* [***here***](/cv).
              
      menu:
          main:
              - identifier: accueil
                name: Accueil
                url: /
                weight : 10
              - identifier: porfolio
                name: Portfolio
                url: /projets/
                weight: 15
              
              - identifier: Curriculum vitæ
                name: Curriculum vitæ
                url: /cv/
                weight: 20

              - identifier: search
                name: Search
                url: /search/
                weight: 50
              


params:
   
    defaultTheme: dark
    disableThemeToggle: true
    displayFullLangName : false
    assets :
      favicon : "ID_axel_carre.png"
    
    homeInfoParams:
        Title: Axel Thauvin
        Subtitle: Étudiant en 3<sup>ème</sup> année à l'EPITA

        Contents :
            - text: Voir [***mes projets***](/projets), ainsi que mes différentes offres de [***cours en ligne***](/cours).
            - text: Vous pouvez trouver mon *Curriculum vitæ* [***ici***](/cv).
        lastNews : Mes derniers projets 📰

        ImageCover : "ID_axel_carre.png"

        buttons:
            #- name: Archive
              #url: "/archive"
            #- name: Github
              #url: "https://github.com/"

        
         
  
    socialIcons:
            - name: "github"
              url: "https://github.com/Axthauvin"
            - name: "twitter"
              url: "https://twitter.com/axthauvin"
            - name: "youtube"
              url: "https://www.youtube.com/channel/UCF6zpti-ice10f9RInxHyFA"
            - name: "hackerrank"
              url: "https://www.hackerrank.com/axthauvin"
            - name: "email"
              url: "http://mailto::axthauvin@gmail.com"
            - name: "itchio"
              url: "https://axthauvin.itch.io/"
            - name: "linkedin"
              url: "https://www.linkedin.com/in/axel-thauvin-37627b260/"
    
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    

    
    ShowCodeCopyButtons: true
    ShowReadingTime: true
    linkFullImages: true
    ShowReadingTime: true
    comments: true
    ShowAuthor: true

    ShowToc: true
    TocOpen: false  
    


    

menu:
    main:
        
        - identifier: accueil
          name: Accueil
          url: /
          weight : 10
        
        - identifier: porfolio
          name: Portfolio
          url: /projets/
          weight: 15
        
        - identifier: Curriculum vitæ
          name: Curriculum vitæ
          url: /cv/
          weight: 20
        
        - identifier: cours
          name: Mes cours
          url: "/cours/"
          weight: 30
        
        - identifier: search
          name: Rechercher
          url: /search/
          weight: 50


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
