baseURL: "https://axthauvin.onrender.com/"
languageCode: fr
title: Axel Thauvin
paginate: 4
theme: "hugo-PaperMod"

defaultContentLanguage: fr

languages:
  fr:
      languageName : Français
      languageAltTitle : Français
      weight: 1
  en:
      dateFormat : January 2, 2006
      languageName : en
      languageAltTitle : English
      weight: 2
      
      params :
          homeInfoParams :
              Title : Axel Thauvin
              ImageCover : "../ImageIllustration - carre.jpg"
              Subtitle : Passionate about computers and programming
              LastNews : Last news 📰
              Contents :
                  - text: Here I will post [***my projects***](../projects), as well as my various offers of [***online courses***](/cours).
                  - text: You can find my *resume* [***here***](/cv).
              
      menu:
          main:
              
              
              - identifier: porfolio
                name: Portfolio
                url: /projets/
                weight: 15
              
              - identifier: Curriculum vitæ
                name: Curriculum vitæ
                url: /cv/
                weight: 20

              - identifier: search
                name: Search
                url: /search/
                weight: 50
              


params:
   
    defaultTheme: dark
    disableThemeToggle: true
    displayFullLangName : false
    assets :
      favicon : "ImageIllustration - carre.jpg"
    
    homeInfoParams:
        Title: Axel Thauvin
        Subtitle: Passionné d'informatique et de programmation

        Contents :
            - text: Ici je posterai [***mes projets***](/projets), ainsi que mes différentes offres de [***cours en ligne***](/cours).
            - text: Vous pouvez trouver mon *Curriculum vitæ* [***ici***](/cv).
        lastNews : Aux dernières nouvelles 📰

        ImageCover : "ImageIllustration - carre.jpg"

        #buttons:
            #- name: Archive
              #url: "/archive"
            #- name: Github
              #url: "https://github.com/"

        
         
  
    socialIcons:
            - name: "github"
              url: "https://github.com/Axthauvin"
            - name: "twitter"
              url: "https://twitter.com/axthauvin"
            - name: "youtube"
              url: "https://www.youtube.com/channel/UCF6zpti-ice10f9RInxHyFA"
            - name: "hackerrank"
              url: "https://www.hackerrank.com/axthauvin"
            - name: "email"
              url: "http://mailto::axthauvin@gmail.com"
            - name: "itchio"
              url: "https://axthauvin.itch.io/"
    
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    

    
    ShowCodeCopyButtons: true
    ShowReadingTime: true
    linkFullImages: true
    ShowReadingTime: true
    comments: true

    ShowToc: true
    TocOpen: false  
    


    

menu:
    main:
        
        
        - identifier: porfolio
          name: Portfolio
          url: /projets/
          weight: 15
        
        - identifier: Curriculum vitæ
          name: Curriculum vitæ
          url: /cv/
          weight: 20
        
        - identifier: cours
          name: Mes cours
          url: "/cours/"
          weight: 30
        
        - identifier: search
          name: Rechercher
          url: /search/
          weight: 50


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
